// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwc8Fw2XClupNSO_heW9Vfu50z6n1G_g',
    appId: '1:283975532588:web:009d6a18efc76828da5189',
    messagingSenderId: '283975532588',
    projectId: 'iitso-trace',
    authDomain: 'iitso-trace.firebaseapp.com',
    storageBucket: 'iitso-trace.firebasestorage.app',
    measurementId: 'G-8Y5EBGKCVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_v_q0cLF5zJZz25INvNjff6qUGRHYjw',
    appId: '1:283975532588:android:f7fb4162c641816dda5189',
    messagingSenderId: '283975532588',
    projectId: 'iitso-trace',
    storageBucket: 'iitso-trace.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6Dw6hz9iNV366j6T8mJpuasRIOSS3Kk',
    appId: '1:283975532588:ios:fef26835a87c9cffda5189',
    messagingSenderId: '283975532588',
    projectId: 'iitso-trace',
    storageBucket: 'iitso-trace.firebasestorage.app',
    iosClientId:
        '283975532588-7ogohoj6lcr7n8dv1mjkljd88pksmgh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trace',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6Dw6hz9iNV366j6T8mJpuasRIOSS3Kk',
    appId: '1:283975532588:ios:fef26835a87c9cffda5189',
    messagingSenderId: '283975532588',
    projectId: 'iitso-trace',
    storageBucket: 'iitso-trace.firebasestorage.app',
    iosClientId:
        '283975532588-7ogohoj6lcr7n8dv1mjkljd88pksmgh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwwc8Fw2XClupNSO_heW9Vfu50z6n1G_g',
    appId: '1:283975532588:web:da02404fb38a8a4bda5189',
    messagingSenderId: '283975532588',
    projectId: 'iitso-trace',
    authDomain: 'iitso-trace.firebaseapp.com',
    storageBucket: 'iitso-trace.firebasestorage.app',
    measurementId: 'G-TRLKD4FHK2',
  );
}
