// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWmLZwYyMyX-5UIZAcOGmlIfh_6fPvA1E',
    appId: '1:659475939688:web:fad27379eda40e289116dd',
    messagingSenderId: '659475939688',
    projectId: 'trace-1bc3a',
    authDomain: 'trace-1bc3a.firebaseapp.com',
    storageBucket: 'trace-1bc3a.firebasestorage.app',
    measurementId: 'G-VZC0ZDFXMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPInSw-9wNTMwN5HLC2704kXgal0ReaUw',
    appId: '1:659475939688:android:1855593525c30b759116dd',
    messagingSenderId: '659475939688',
    projectId: 'trace-1bc3a',
    storageBucket: 'trace-1bc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtCj1kj02tPX89UqZ3xF0n9Klxl5b3qk',
    appId: '1:659475939688:ios:0ca6feede99300489116dd',
    messagingSenderId: '659475939688',
    projectId: 'trace-1bc3a',
    storageBucket: 'trace-1bc3a.firebasestorage.app',
    iosBundleId: 'com.example.trace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtCj1kj02tPX89UqZ3xF0n9Klxl5b3qk',
    appId: '1:659475939688:ios:0ca6feede99300489116dd',
    messagingSenderId: '659475939688',
    projectId: 'trace-1bc3a',
    storageBucket: 'trace-1bc3a.firebasestorage.app',
    iosBundleId: 'com.example.trace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWmLZwYyMyX-5UIZAcOGmlIfh_6fPvA1E',
    appId: '1:659475939688:web:356c6f1ac8d63a769116dd',
    messagingSenderId: '659475939688',
    projectId: 'trace-1bc3a',
    authDomain: 'trace-1bc3a.firebaseapp.com',
    storageBucket: 'trace-1bc3a.firebasestorage.app',
    measurementId: 'G-LTE23FHL7R',
  );
}
